server = "https://10.0.0.12:3000"

[[configs]]
id = "blackbeard-cpu"
type = "temperature"
endpoint = "https://10.0.0.12:3000/sensor_data"
interval = 5

[[configs]]
id = "blackbeard-gpu"
type = "temperature"
endpoint = "https://10.0.0.12:3000/sensor_data"
interval = 10
